services:
  _defaults:
    public: true

  cdigruttola.module.electronicinvoicefields.bundle.form.admin.address_customer_type:
    class: 'cdigruttola\Module\Electronicinvoicefields\Form\Admin\AddressCustomerTypeType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  cdigruttola.module.electronicinvoicefields.core.form.identifiable_object.builder.address_customer_type_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
    arguments:
      - 'cdigruttola\Module\Electronicinvoicefields\Form\Admin\AddressCustomerTypeType'
      - '@cdigruttola.module.electronicinvoicefields.core.form.identifiable_object.data_provider.address_customer_type_form_data_provider'

  cdigruttola.module.electronicinvoicefields.core.form.identifiable_object.data_provider.address_customer_type_form_data_provider:
    class: 'cdigruttola\Module\Electronicinvoicefields\Core\Domain\AddressCustomerType\AddressCustomerTypeFormDataProvider'
    arguments:
      - '@cdigruttola.module.electronicinvoicefields.repository.einvoice_customer_type'

  cdigruttola.module.electronicinvoicefields.core.form.identifiable_object.handler.address_customer_type_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@cdigruttola.module.electronicinvoicefields.core.form.identifiable_object.data_handler.address_customer_type_form_data_handler'

  cdigruttola.module.electronicinvoicefields.core.form.identifiable_object.data_handler.address_customer_type_form_data_handler:
    class: 'cdigruttola\Module\Electronicinvoicefields\Form\DataHandler\AddressCustomerTypeFormDataHandler'
    arguments:
      - '@cdigruttola.module.electronicinvoicefields.repository.einvoice_customer_type'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"

  cdigruttola.module.electronicinvoicefields.form.configuration_type:
    class: 'cdigruttola\Module\Electronicinvoicefields\Form\Admin\ConfigurationType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  cdigruttola.module.electronicinvoicefields.configuration.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@cdigruttola.module.electronicinvoicefields.configuration.form_provider'
      - 'cdigruttola\Module\Electronicinvoicefields\Form\Admin\ConfigurationType'
      - 'EInvoiceConfigurationForm'

  cdigruttola.module.electronicinvoicefields.configuration.form_provider:
    class: cdigruttola\Module\Electronicinvoicefields\Form\DataProvider\ConfigurationFormDataProvider
    arguments:
      - '@cdigruttola.module.electronicinvoicefields.configuration'

  cdigruttola.module.electronicinvoicefields.configuration:
    class: cdigruttola\Module\Electronicinvoicefields\Form\DataConfiguration\ConfigurationDataConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'
