services:
  _defaults:
    public: true

  cdigruttola.module.electronicinvoicefields.module:
    class: Electronicinvoicefields
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'electronicinvoicefields'

  cdigruttola.module.electronicinvoicefields.repository.einvoice_customer_type:
    class: cdigruttola\Module\Electronicinvoicefields\Repository\EinvoiceCustomerTypeRepository
    public: true
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - cdigruttola\Module\Electronicinvoicefields\Entity\EinvoiceCustomerType

  cdigruttola.module.electronicinvoicefields.repository.einvoice_address:
    class: cdigruttola\Module\Electronicinvoicefields\Repository\EinvoiceAddressRepository
    public: true
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - cdigruttola\Module\Electronicinvoicefields\Entity\EinvoiceAddress
