admin_electronic_invoice_configuration:
  path: /einvoice/configuration
  methods: [GET]
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminElectronicInvoiceController::indexConfiguration'

admin_electronic_invoice_configuration_save:
  path: /einvoice/configuration
  methods: [POST, PATCH]
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminElectronicInvoiceController::saveConfiguration'

admin_address_customer_type:
  path: /address-customer-type
  methods: [ GET ]
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminAddressCustomerTypeController::indexAction'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    _legacy_link: 'AdminAddressCustomerTypeController'

admin_address_customer_type_create:
  path: /address-customer-type/new
  methods: [ GET, POST ]
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminAddressCustomerTypeController::createAction'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    _legacy_link: 'AdminAddressCustomerTypeController:add'

admin_address_customer_type_edit:
  path: /address-customer-type/edit/{addressCustomerTypeId}
  methods: [ GET, POST ]
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminAddressCustomerTypeController::editAction'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    _legacy_link: 'AdminAddressCustomerTypeController:edit'

admin_address_customer_type_filter:
  path: /address-customer-type
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Common:searchGrid'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    gridDefinitionFactoryServiceId: cdigruttola.module.electronicinvoicefields.core.grid.definition.factory.address_customer_type
    redirectRoute: admin_address_customer_type
    _legacy_link: 'AdminAddressCustomerTypeController:submitFiltertype'

admin_address_customer_type_delete:
  path: /address-customer-type/delete/{addressCustomerTypeId}
  methods: [ POST ]
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminAddressCustomerTypeController::deleteAction'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    _legacy_link: 'AdminAddressCustomerTypeController:delete'

admin_address_customer_type_toggle_status:
  path: /address-customer-type/toggle-status/{addressCustomerTypeId}
  methods: POST
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminAddressCustomerTypeController::toggleStatusAction'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    _legacy_link: 'AdminAddressCustomerTypeController:enableSelection'
    _legacy_parameters:
      id_zone: addressCustomerTypeId
  requirements:
    addressCustomerTypeId: \d+

admin_address_customer_type_toggle_need_invoice:
  path: /address-customer-type/toggle-need-invoice/{addressCustomerTypeId}
  methods: POST
  defaults:
    _controller: 'cdigruttola\Module\Electronicinvoicefields\Controller\Admin\AdminAddressCustomerTypeController::toggleNeedInvoiceAction'
    _legacy_controller: 'AdminAddressCustomerTypeController'
    _legacy_link: 'AdminAddressCustomerTypeController:enableInvoiceSelection'
    _legacy_parameters:
      id_zone: addressCustomerTypeId
  requirements:
    addressCustomerTypeId: \d+
